amazingthings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('amazingthings/', views.amazingthings_index, name='index'),
    path('amazingthings/<int:thing_id>/', views.amazingthings_detail, name='detail'),
    path('amazingthings/create/', views.ThingCreate.as_view(), name='things_create'),
    path('amazingthings/<int:pk>/update/', views.ThingUpdate.as_view(), name='things_update'),
    path('amazingthings/<int:pk>/delete/', views.ThingDelete.as_view(), name='things_delete'),
    path('amazingthings/<int:thing_id>/add_events/', views.add_events, name='add_events'),
    path('amazingthings/<int:thing_id>/assoc_program/<int:program_id>/', views.assoc_program, name='assoc_program'),
    path('programs/', views.ProgramList.as_view(), name='programs_index'),
    path('programs/<int:pk>/', views.ProgramDetail.as_view(), name='programs_detail'),
    path('programs/create/', views.ProgramCreate.as_view(), name='programs_create'),
    path('programs<int:pk>/update/', views.ProgramUpdate.as_view(), name='programs_update'),
    path('programs/<int:pk>/delete', views.ProgramDelete.as_view(), name='programs_delete')
]

main_app/models.py
from django.db import models
from django.urls import reverse

class Program(models.Model):
    name = models.CharField(max_length=100)
    kind = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('programs_detail', kwargs={'pk': self.id})



# Create your models here.
class Thing(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.CharField(max_length=450)
    age = models.IntegerField()
    programs = models.ManyToManyField(Program)
    
    def __str__(self):
      return f"Thing: {self.name} Id: {self.id}"

      # Add this method
    def get_absolute_url(self):
        return reverse('detail', kwargs={'thing_id': self.id})

TYPES = (
    ('N', 'Nature'),
    ('V', 'Visit'),
    ('T', 'Tour')
)

class Events(models.Model):
    date = models.DateField()
    type = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=TYPES,
        # set the default value for meal to be 'B'
        default=TYPES[0][0]
    )

# Create a thing ForeignKey (in psql)
    thing = models.ForeignKey(Thing, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_type_display()} on {self.date}"

        class Meta:
             ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Events

class EventsForm(ModelForm):
  class Meta:
    model = Events
    fields = ['date', 'type']

main_app/views.py
from django.shortcuts import render, redirect
# from asyncio import events
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.http import HttpResponse
from .models import Thing, Program
from .forms import EventsForm

# Create your views here.
class ThingCreate(CreateView):
  model = Thing
  fields = ['name', 'location', 'description', 'age']

class ThingUpdate(UpdateView):
  model = Thing
  fields = ['name', 'location', 'description', 'age']

class ThingDelete(DeleteView):
  model = Thing
  success_url = '/amazingthings/'  

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def amazingthings_index(request):
    amazingthings = Thing.objects.all()
    return render(request, 'amazingthings/index.html', { 'amazingthings': amazingthings })

def amazingthings_detail(request, thing_id):
  amazingthing = Thing.objects.get(id=thing_id)
  programs_thing_doesnt_have = Program.objects.exclude(id__in = amazingthing.programs.all().values_list('id')) #try thing.programs
  events_form = EventsForm()
  return render(request, 'amazingthings/detail.html', {
    'amazingthing': amazingthing, 'events_form': events_form,
    'programs': programs_thing_doesnt_have
  })


def add_events(request, thing_id):
    form = EventsForm(request.POST)

    if form.is_valid():
      new_events = form.save(commit=False)
      new_events.thing_id = thing_id
      new_events.save()
    return redirect('detail', thing_id=thing_id)



def assoc_program(request, thing_id, program_id):
  Thing.objects.get(id=thing_id).programs.add(program_id)
  return redirect('detail', thing_id=thing_id)



class ProgramList(ListView):
  model = Program

class ProgramDetail(DetailView):
  model = Program

class ProgramCreate(CreateView):
  model = Program
  fields = '__all__'

class ProgramUpdate(UpdateView):
  model = Program
  fields = ['name', 'kind']

class ProgramDelete(DeleteView):
  model = Program
  success_url = '/programs/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About Amazing Things</h1>
<hr />
<p>Explore the world's most amazing things!</p>

{% endblock %}

main_app/templates/amazingthings/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Details of the Amazing Things</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ amazingthing.name }}</span>
        <p>Name: {{ amazingthing.name }}</p>
        <p>Location: {{ amazingthing.location }}</p>
        {% if amazingthing.age > 0 %}
          <p>Description: {{ amazingthing.description }}</p>
        {% else %}
          <p>Age: Unknown</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'things_update' amazingthing.id %}">Edit</a>
        <a href="{% url 'things_delete' amazingthing.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">

    <form method="post" action="{% url 'add_events' amazingthing.id %}">
        {% csrf_token %}
        {{ events_form.as_p }}
        <input type="submit" class="btn" value="Add Event">
      </form>

    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Event</th></tr>
      </thead>
      <tbody>
        {% for events in amazingthing.events_set.all %}
          <tr>
            <td>{{events.date}}</td>
            <td>{{events.get_type_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ amazingthing.name }}'s Programs</h3>
    {% if amazingthing.programs.count %}
      {% for program in amazingthing.programs.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                <span style="color:blueviolet">{{ program.name }}</span>
                <p>{{ program.kind }}</p>
              </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Programs</h5>
    {% endif %}
  </div>
</div>

<div class="col s6">
    <h3>Available Programs</h3>
    {% if programs.count %}
      {% for program in programs.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color:blueviolet">{{ program.name }}</span>
              <p>{{ program.kind }}</p>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_program' amazingthing.id program.id %}" method="post"> 
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{thing.name}} Already Has All Programs Available</h5>
    {% endif %}
  </div>



<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    const selectEl = document.getElementById('id_type');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/amazingthings/index.html
{% extends 'base.html' %}
{% block content %}


<h1>Amazing Things List</h1>
{% for amazingthing in amazingthings %}
  <div class="card">
      <a href="{% url 'detail' amazingthing.id %}">
      <div class="card-content">
      <span style="color:green" class="card-title">{{ amazingthing.name }}</span>
      <h6>Location: {{ amazingthing.location }}</h6>
      <p><strong>How many years has it been there? </strong> {{ amazingthing.age }}</p>
      <p><strong>What is it?</strong> {{ amazingthing.description }}</p>
      {% if amazingthing.age > 0 %}
      {% else %}
        <p><strong>Age:</strong> Unknown</p>
      {% endif %}
    </div>
   </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Amazing Things</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Amazing Things</a></li>
        </ul>
        <ul class="right">
					<li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'programs_create' %}">Add A Program</a></li>
					<li><a href="{% url 'programs_index' %}">View All Programs</a></li>
					<li><a href="{% url 'index' %}">View All My Things</a></li>
					<li><a href="{% url 'things_create' %}">Add A Thing</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Amazing Things &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <p>
        {% load static %}
        <img src="{% static 'main_app/static/img/forest.jpeg' %}" alt="My image"></p>
</body>
</html>

main_app/templates/main_app/program_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Program</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'programs_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/program_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Program Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ program.name }}</span>
        <p>Kind: {{ program.kind }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'programs_update' program.id %}">Edit</a>
        <a href="{% url 'programs_delete' program.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/program_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Program</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/program_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Program List</h1>

{% for program in program_list %}
  <a href="{% url 'programs_detail' program.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ program.name }}</span>
            <p>Kind: {{ program.kind }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/thing_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Thing</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' thing.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/thing_form.html
{% extends 'base.html' %}

{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Thing</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}